swagger: '2.0'
info:
  version: '1.0'
  title: Project API
  description: |-
    ##### Dokumentasi API Collection

    This collection contains sample requests from this \[**API**\](http://localhost/arkatama/project_api/)

    It contains following request

    1. task_categories
        1. Insert
        2. Update
        3. list
        4. select
        5. delete
    2. tasks
        1. Insert
        2. Update
        3. list
        4. select
        5. delete

    EndFragmen
  contact: {}
host: localhost
basePath: /arkatama/project_api
securityDefinitions: {}
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /task_categories:
    post:
      summary: insert-task_categories
      tags:
        - task_categories
      operationId: insert-task_categories
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/insert-task_categories-request'
      responses:
        '200':
          description: ''
          headers: {}
  /task_categories/update/id_categories:
    post:
      summary: update-task_categories
      tags:
        - task_categories
      operationId: update-task_categories
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/update-task_categories-request'
      responses:
        '200':
          description: ''
          headers: {}
  /task_categories/list:
    get:
      summary: list-task_categories
      tags:
        - task_categories
      operationId: list-task_categories
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: page
          in: query
          required: true
          type: integer
          format: int32
          description: ''
        - name: per-page
          in: query
          required: true
          type: integer
          format: int32
          description: ''
      responses:
        '200':
          description: ''
          headers: {}
  /task_categories/index:
    get:
      summary: select-task_categories
      tags:
        - task_categories
      operationId: select-task_categories
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: id_categories
          in: query
          required: true
          type: integer
          format: int32
          description: ''
      responses:
        '200':
          description: ''
          headers: {}
  /task_categories/index/id_categories/8:
    delete:
      summary: delete-task_categories
      tags:
        - task_categories
      operationId: delete-task_categories
      deprecated: false
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
  /tasks:
    post:
      summary: insert-tasks
      tags:
        - tasks
      operationId: insert-tasks
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/insert-tasks-request'
      responses:
        '200':
          description: ''
          headers: {}
  /tasks/update/id_tasks/3:
    post:
      summary: update-tasks
      tags:
        - tasks
      operationId: update-tasks
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/update-tasks-request'
      responses:
        '200':
          description: ''
          headers: {}
  /tasks/index/id_tasks/3:
    get:
      summary: select-tasks
      tags:
        - tasks
      operationId: select-tasks
      deprecated: false
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
    delete:
      summary: Delete-tasks
      tags:
        - tasks
      operationId: Delete-tasks
      deprecated: false
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
  /tasks/list:
    get:
      summary: list-tasks
      tags:
        - tasks
      operationId: list-tasks
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: page
          in: query
          required: true
          type: integer
          format: int32
          description: ''
        - name: per-page
          in: query
          required: true
          type: integer
          format: int32
          description: ''
      responses:
        '200':
          description: ''
          headers: {}
definitions:
  insert-task_categories-request:
    title: insert-task_categories-request
    example:
      name: Annualy
    type: object
    properties:
      name:
        type: string
    required:
      - name
  update-task_categories-request:
    title: update-task_categories-request
    example:
      name: Sulit
    type: object
    properties:
      name:
        type: string
    required:
      - name
  insert-tasks-request:
    title: insert-tasks-request
    example:
      category_id: '2'
      tittle: Tugas Kecil
      description: Tugas ini membuat sebuah dokumen
      start_date: '2022-10-29'
      finish_date: '2022-11-09'
      status: New
      doc_url: Kirim jawaban disini
    type: object
    properties:
      category_id:
        type: string
      tittle:
        type: string
      description:
        type: string
      start_date:
        type: string
      finish_date:
        type: string
      status:
        type: string
      doc_url:
        type: string
    required:
      - category_id
      - tittle
      - description
      - start_date
      - finish_date
      - status
      - doc_url
  update-tasks-request:
    title: update-tasks-request
    example:
      category_id: '3'
    type: object
    properties:
      category_id:
        type: string
    required:
      - category_id
tags:
  - name: task_categories
  - name: tasks
